### PR TITLE
Fix for Truenas Scale midctl args not accepting 'paths'

### PR DESCRIPTION
**Pull request by edhull**
It looks like midctl now only accepts a payload of the following format for NFS shares: 
```
[
  {
    "id": 1,
    "path": "",
    "aliases": [],
    "comment": "Test",
    "hosts": [],
    "ro": false,
    "quiet": false,
    "maproot_user": "",
    "maproot_group": "",
    "mapall_user": "",
    "mapall_group": "",
    "security": [],
    "enabled": true,
    "networks": [],
    "locked": false
  }
]
```

which was not compatible with this module trying to pass in a list of 'paths'.

The result was ansible failing with:
`FAILED! => {"changed": false, "msg": "Error creating NFS export \"test\": midclt exited with status 1: \"b'[EINVAL] sharingnfs_create.paths: Field was not expected\\n[EINVAL] sharingnfs_create.path: attribute required\\n'\""}`

This replaces the 'paths' key with 'path', resulting in a 1:1 mapping between NFS shares and exported paths.

Note: This was tested on Truenas Scale 22.12.2 / Linux truenas0 5.15.79+truenas #1 SMP Mon Apr 10 14:00:27 UTC 2023 x86_64 GNU/Linux

### CODE REVIEW

**Comment by arensb** [comment]
Thanks for finding this. In fact, this even solves a different problem I'd been wrestling with.

I don't suppose you happen to know which version introduced this change, do you? The latest stable TrueNAS CORE still uses `paths`.

**Comment by edhull** [comment]
> Thanks for finding this. In fact, this even solves a different problem I'd been wrestling with.
> 
> I don't suppose you happen to know which version introduced this change, do you? The latest stable TrueNAS CORE still uses `paths`.

I'm afraid not, but Scale 22.12.2 has only been available since early April so this could be a fairly recent change. I suspect it might be worth leaving this PR open until Core catches up, but it's worth flagging for Scale users!

**Comment by arensb** [comment]
The change seems to have been introduced in https://github.com/truenas/middleware/commit/558ea76887b99134f16b11914671b31e3847def4 , which is part of the TrueNAS SCALE 22.12.2 release. It's not part of CORE, and who knows when it will be.
So while I don't mind rewriting the Ansible front-end to use `path` rather than `paths`, on the back end, I think it'll have to support multiple versions of middlewared.
I think it'll be necessary to add midclt calls to `system.product_name`, `system.product_type`, `system.version`, and/or `system.info`. And maybe create one or two classes for this, depending what makes the most sense.

**Comment by edhull** [comment]
> @edhull Could you please take a look at the `pr/1-sharing-nfs` branch?: https://github.com/arensb/ansible-truenas/tree/pr/1-sharing-nfs I've split the code between `nfs1` and `nfs2` (mostly your code). I've also tweaked nfs2 to use the path (singular) as the identifier, meaning that the name is now optional, and things should be much more intuitive. `__main__` now just checks the version of TrueNAS to see which NFS code to run. I had to do some guessing there, so could you please check that it works on your end?

I've run the pr/1-sharing-nfs branch against Scale and it runs without any issues. Many thanks for your effort!

**Pull request closed without merging**
